// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.1_@types+node@24.9.1_@vue+compiler-sfc@3.5.25_better-sql_d9ddbd7439cac68dd5805ec37d773599/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.1_@types+node@24.9.1_@vue+compiler-sfc@3.5.25_better-sql_d9ddbd7439cac68dd5805ec37d773599/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.1_@types+node@24.9.1_@vue+compiler-sfc@3.5.25_better-sql_d9ddbd7439cac68dd5805ec37d773599/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/nuxt-site-config/dist/runtime/app/plugins/0.siteConfig.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.1_@types+node@24.9.1_@vue+compiler-sfc@3.5.25_better-sql_d9ddbd7439cac68dd5805ec37d773599/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+content@3.8.2_better-sqlite3@12.5.0_magicast@0.5.1/node_modules/@nuxt/content/dist/runtime/plugins/websocket.dev.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.1_@types+node@24.9.1_@vue+compiler-sfc@3.5.25_better-sql_d9ddbd7439cac68dd5805ec37d773599/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.1_@types+node@24.9.1_@vue+compiler-sfc@3.5.25_better-sql_d9ddbd7439cac68dd5805ec37d773599/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.1_@types+node@24.9.1_@vue+compiler-sfc@3.5.25_better-sql_d9ddbd7439cac68dd5805ec37d773599/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.1_@types+node@24.9.1_@vue+compiler-sfc@3.5.25_better-sql_d9ddbd7439cac68dd5805ec37d773599/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.1_@types+node@24.9.1_@vue+compiler-sfc@3.5.25_better-sql_d9ddbd7439cac68dd5805ec37d773599/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.1_@types+node@24.9.1_@vue+compiler-sfc@3.5.25_better-sql_d9ddbd7439cac68dd5805ec37d773599/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.1_@types+node@24.9.1_@vue+compiler-sfc@3.5.25_better-sql_d9ddbd7439cac68dd5805ec37d773599/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.25_db0@0.3.4_better-sqlite3@12.5.0__eslint@9._427c5910c7107767e03d970dce041a5f/node_modules/@nuxtjs/i18n/dist/runtime/plugins/switch-locale-path-ssr.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.25_db0@0.3.4_better-sqlite3@12.5.0__eslint@9._427c5910c7107767e03d970dce041a5f/node_modules/@nuxtjs/i18n/dist/runtime/plugins/route-locale-detect.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.25_db0@0.3.4_better-sqlite3@12.5.0__eslint@9._427c5910c7107767e03d970dce041a5f/node_modules/@nuxtjs/i18n/dist/runtime/plugins/preload.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.25_db0@0.3.4_better-sqlite3@12.5.0__eslint@9._427c5910c7107767e03d970dce041a5f/node_modules/@nuxtjs/i18n/dist/runtime/plugins/dev.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.25_db0@0.3.4_better-sqlite3@12.5.0__eslint@9._427c5910c7107767e03d970dce041a5f/node_modules/@nuxtjs/i18n/dist/runtime/plugins/i18n.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+robots@5.6.7_h3@1.15.4_magicast@0.5.1_vue@3.5.25_typescript@5.9.3__zod@4.1.13/node_modules/@nuxtjs/robots/dist/runtime/app/plugins/robot-meta.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-og-image@5.1.12_@unhead+vue@2.0.19_vue@3.5.25_typescript@5.9.3___h3@1.15.4_magicas_aadd009b9b577d11ac5194818822e118/node_modules/nuxt-og-image/dist/runtime/app/plugins/og-image-canonical-urls.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-og-image@5.1.12_@unhead+vue@2.0.19_vue@3.5.25_typescript@5.9.3___h3@1.15.4_magicas_aadd009b9b577d11ac5194818822e118/node_modules/nuxt-og-image/dist/runtime/app/plugins/route-rule-og-image.server.js")> &
  InjectionType<typeof import("../../node_modules/nuxt-site-config/dist/runtime/app/plugins/i18n.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parser@7.28.5_@nuxt+content@3.8.2_better-sqlite3@12.5.0_magicast@_fc4915e8f02cf786a5297e6833cca1a2/node_modules/@nuxt/ui/dist/runtime/plugins/colors.js")> &
  InjectionType<typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.1_@types+node@24.9.1_@vue+compiler-sfc@3.5.25_better-sql_d9ddbd7439cac68dd5805ec37d773599/node_modules/nuxt/dist/app/plugins/warn.dev.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.1_@types+node@24.9.1_@vue+compiler-sfc@3.5.25_better-sql_d9ddbd7439cac68dd5805ec37d773599/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")> &
  InjectionType<typeof import("../../app/plugins/error-handler")> &
  InjectionType<typeof import("../../app/plugins/lenis.client")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@2.5.1_@types+node@24.9.1_@vue+compiler-sfc@3.5.25_better-sql_d9ddbd7439cac68dd5805ec37d773599/node_modules/nuxt/dist/pages/runtime/plugins/prerender.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.25_db0@0.3.4_better-sqlite3@12.5.0__eslint@9._427c5910c7107767e03d970dce041a5f/node_modules/@nuxtjs/i18n/dist/runtime/plugins/ssg-detect.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt-site-config:init' | 'nuxt:browser-devtools-timing' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'i18n:plugin:switch-locale-path-ssr' | 'i18n:plugin:route-locale-detect' | 'i18n:plugin:preload' | 'i18n:dev' | 'i18n:plugin' | 'nuxt-site-config:i18n' | '@nuxt/icon' | 'nuxt:checkIfLayoutUsed' | 'i18n:plugin:ssg-detect'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
